# Generated by Django 4.2.4 on 2023-08-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectorlog',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
