# Generated by Django 4.2.4 on 2023-08-16 22:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['.py'])], verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='InspectorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.uploadedfile', verbose_name='Файл')),
            ],
        ),
    ]
